"use client";

import type { Metadata } from "next";

import { Navbar } from "@/components";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        {/* <Navbar /> */}
        <div>{children}</div>
      </body>
    </html>
  );
}
